title: "Xuyi's Life"             # 网站标题
url: https://xuyi.zone           # 网站域名
description: Her life in my eyes # 网站描述

img: /assets/img                 # 图片路径
css: /assets/css

email: professordeng@qq.com

socials:
- name: github
  url: https://github.com/xuyilife/xuyilife.github.io

nav:
- name: HOME
  path: /
- name: WE
  path: /pages/we
- name: SHE
  path: /pages/she
- name: HE
  path: /pages/he

